Little FlxBackdrop optimization
HaxeFlixel/flixel-addons pull request #394
Opened 2023-06-24 04:20 UTC by Sword352

This little pull request just replace the way the `spacing` FlxPoint is initialized (getting a recycled point from the pool, basically).

2023-06-24 04:56 UTC, MemeHovy commented
nice 👍

2023-06-25 16:53 UTC, Geokureli requested changes
good catch on that old comment, but now you've awakened the grammar nazi in me

2023-06-25 16:53 UTC, Geokureli commented on flixel/addons/display/FlxBackdrop.hx
> +	 * @param   repeatAxes  The axis where the backdrop should repeat to.
```suggestion
	 * @param   repeatAxes  The axes on which to repeat. The default, `XY` will tile the entire camera.
```

2023-06-26 07:57 UTC, Sword352 commented on flixel/addons/display/FlxBackdrop.hx
> +	 * @param   repeatAxes  The axis where the backdrop should repeat to.
fair, i suck at english lol, thanks

2023-06-26 16:49 UTC, Geokureli approved these changes

2023-06-26 16:50 UTC, merged